services:
  telegraf:
    image: telegraf:1.23
    environment:
      INFLUX_TOKEN: ${INFLUX_TOKEN_CLOUD}
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: unless-stopped
